name: custom_animated_bottom_navigation_bar
description: Animated Bottom Navigation Bar Widget implementation inspired by https://dribbble.com/shots/7134849-Simple-Tab-Bar-Animation
version: 1.2.0
homepage: https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #changed the package version
  showcaseview: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
